apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
    namespace: staging
    labels:
        app: mysql
spec:
    replicas: 3
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql:latest
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: ruda@2023
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - name: data
                        mountPath: /var/lib/mysql
            volumes:
                - name: data
                  persistentVolumeClaim:
                      claimName: ruda-pvc
