apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ruda-pvc
    labels:
        run: ruda-pvc
    namespace: staging
spec:
    storageClassName: local-storage
    volumeName: ruda-pv
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 30Gi
